services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: liveinfo
      POSTGRES_USER: liveinfo
      POSTGRES_PASSWORD: liveinfo
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  influxdb:
    image: influxdb:2.7-alpine
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: liveinfo
      DOCKER_INFLUXDB_INIT_PASSWORD: liveinfo
      DOCKER_INFLUXDB_INIT_ORG: liveinfo
      DOCKER_INFLUXDB_INIT_BUCKET: liveinfo
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: liveinfo!
    ports:
      - '8086:8086'
    volumes:
      - ./data/influxdb:/var/lib/influxdb2
      - ./data/influxdb-config:/etc/influxdb2
